config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :jungles  do
    resources :plants, only: [:new, :create]
  end
  resources :plants, only: [ :update, :edit, :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jungle.rb
class Jungle < ApplicationRecord
  has_many :plants, dependent: :destroy

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :jungle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jungles_controller.rb
class JunglesController < ApplicationController
  before_action :find_jungle, only: [:show, :edit, :update, :destroy]

  def index
    @jungles = Jungle.all.limit(12)

    @markers = @jungles.geocoded.map do |jungle|
      {
        lat: jungle.latitude,
        lng: jungle.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { jungle: jungle})
      }
    end
 end

  def show
  end

  def new
    @jungle = Jungle.new
  end

  def create
    @jungle = Jungle.new(jungle_params)
    if  @jungle.save
      redirect_to @jungle, notice: 'jungle was created'
    else
      render :new
    end
  end

  def destroy
  end

  private

  def find_jungle
    @jungle = Jungle.find(params[:id])
  end

  def jungle_params
    params.require(:jungle).permit(:name, :banner_url)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @jungles = Jungle.order(created_at: :desc).limit(7)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :find_jungle, except: [ :edit, :update, :destroy]
  before_action :find_plant, only: [ :edit, :update, :show]

  # def index
  #   @plants = Plant.all
  # end

  # def show
  # end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.jungle = @jungle
    if @plant.save
      redirect_to jungle_path(@jungle), notice: 'plant was created!'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @plant.update(plant_params)

      redirect_to jungle_path(@plant.jungle_id), notice: 'plant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    jungle = @plant.jungle
    @plant.destroy
    redirect_to jungle_path(jungle), notice: 'plant was deleted'
  end

  private

  def find_jungle
    @jungle = Jungle.find(params[:jungle_id])
  end

  def plant_params
    params.require(:plant).permit(:name, :nickname)
  end

  def find_plant
    @plant = Plant.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jungles_helper.rb
module JunglesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/jungles/_info_window.html.erb
<h2><%= jungle.name %></h2>
<p><%= jungle.location %></p>

app/views/jungles/_jungle-cards.html.erb
<div class= "jungle-cards">
      <% @jungles.each do |jungle| %>

        <div class="card-jungle" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= jungle.banner_url %>);">
          <%= link_to jungle_path(jungle) do %>
            <h4><%= jungle.name %></h4>
          <% end %>

       </div>

      <% end %>

</div>

app/views/jungles/_map.html.erb
<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/jungles/_search-bar.html.erb
<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-success">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

app/views/jungles/edit.html.erb
Edit your jungle

<%= simple_form_for(@jungle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
      <%= f.input :banner_url %>
  </div>

   <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


<%= link_to 'show', @jungle %> |
<%= link_to 'back', jungles_path %>

app/views/jungles/index.html.erb
  <div class ="row justify-content-center central-col p-5">

    <div class="col-2 menu-col">
      <ul class="list-unstyled">

        <li><%= link_to "Create My Own Jungle", new_jungle_path %></li>
        <li> <%= link_to root_path do %>
          <i class="fas fa-door-closed"></i> Home </li>
           <% end %>
        <li> <%= link_to root_path do %>
              <i class="fas fa-seedling"></i> My Jungles </li>
           <% end %>
        <li> <%= link_to root_path do %>
              <i class="fab fa-readme"></i> My Posts </li>
           <% end %>

        <li> <%= link_to root_path do %>

           <i class="fas fa-book-dead"></i></i> UJC Blog </li>
           <% end %>


      </ul>
    </div>




    <div class="col-6  cards-col">
      <div>

        <%= render "search-bar" %>

        <div class="">
<!--           <h6> x jungles match to your search</h6>
 -->        </div>

        <%= render "jungle-cards" %>
      </div>

        <%= link_to "Back", root_path, class: "btn btn-outline-dark mt-3" %>

         <%= link_to "Next", root_path, class: "btn btn-outline-dark mt-3" %>
    </div>

    <div class="col-4 map-col ">

      <div class="map-div ">
        <div>
        <%= render "map" %>
        </div>


        <div class="link mt-3">
           <%= link_to "Create your jungle", new_jungle_path, class: "btn btn-warning" %>
        </div>

      </div>

    </div>

  </div>

app/views/jungles/new.html.erb
<div class="container new-jungle-container mt-5  sharing-simple-form">
 <%= simple_form_for(@jungle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "i.e My InnGarden" %>
    <%= f.input :location, placeholder: "i.e Berlin, Germany" %>
    <%= f.input :banner_url %>

  </div>

   <div class="form-actions">
    <%= f.button :submit, class:"btn btn-warning" %>
  </div>
<% end %>


<%= link_to 'show', @jungle %> |
<%= link_to 'back', jungles_path %>
</div>

app/views/jungles/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @jungle.banner_url %>);">
  <div class="container">
    <h1><%= @jungle.name %></h1>
  </div>
</div>

<div class="container">

  <div class="container">
    <h4><%= link_to 'Add a plant!', new_jungle_plant_path(@jungle) %></h4>
    <div class="cards">
      <% @jungle.plants.each do |plant| %>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image %>);">
          <h4><%= plant.name %></h4>
          <p> <%= link_to 'edit', edit_plant_path(plant) %> </p>

          <p> <%= link_to '🗑', plant_path(plant.id), method: :delete %> </p>
        </div>
      <% end %>
    </div>

    <%= link_to 'Edit', edit_jungle_path(@jungle) %> |
    <%= link_to 'Back', jungles_path %> |
    <%= link_to 'create a plant', new_jungle_plant_path(@jungle) %>


  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrbanJunglesClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link href='https://api.mapbox.com/mapbox-gl-js/v2.0.1/mapbox-gl.css' rel='stylesheet' />





    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body class="h-100">
    <div class="wrapper">
    <%= render 'shared/navbar' %>

    <%= yield %>

    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_home-cards.html.erb
<div class="cards home-jungle-cards">
      <% @jungles.each do |jungle| %>

        <div class="card-category home-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= jungle.banner_url %>);">
        <%= link_to jungle_path(jungle) do %>
        <br>
        <h4><%= jungle.name %></h4><br>
        <% end %>
      </div>
      <% end %>
      <div class="card-category home-cards" style="background-image: linear-gradient(#8BC34A, rgb(139, 195, 74,0.59)), url('https://images.unsplash.com/photo-1561819775-612449efea85?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1950&q=80');">
        <%= link_to "Explore" , jungles_path, class:"see-all-jungles"  %>
        <br>


      </div>
    </div>

app/views/pages/_sections.html.erb
<div class="row create-section">
  <div class="create-container container d-flex justify-content-between">

    <div class="col-6 create-section--image">
      <%= image_tag "monstera.jpg", alt: "monstera plant", height: 400,  width: 600 %>
    </div>


    <div class="col-4 create-section--text d-flex align-items-center">
       Create that especial place for your urban jungle, where it is only  and exclusively about your plants!
    </div>
  </div>


</div>

<div class="row connect-section">

  <div class="connect-container container d-flex justify-content-between">

      <div class="col-4 connect-section--text d-flex align-items-center">
        Connect with other plant-moms and dads around the world and make friends with your same green passion
      </div>

      <div class="col-6 connect-section--image">
        <%= image_tag "ficus1.jpg", alt: "Le Wagon", width: 600 %>
      </div>

  </div>

</div>



<div class="row share-section">

  <div class="connect-container container d-flex justify-content-between">

    <div class="col-6 share-section--image">
      <%= image_tag "ficus.jpg", alt: "Le Wagon", width: 600 %>
    </div>

    <div class="col-4 share-section-text d-flex align-items-center">
        Share tips and tricks about plant care and keep your green babies fit and growing!
    </div>

  </div>

</div>


<div class="row justify-content-center cards-section">

     <%= render 'home-cards' %>

</div>


<div class="row connect-section">

  <div class="col-7">
    Did you know?
  </div>

  <div class="col-4">
     Ready to start your own jungle adventure? <br>
     Sign up !
  </div>

  <div class="col-1"></div>

</div>

app/views/pages/home.html.erb
<div class="row main-banner ">
  <div class="container main-banner-objects d-flex">

    <div class="col-6">

      <h1>Urban Jungles Club </h1>
      <h2> Share your home jungle and be part of the community that never stops growing!</h2>
      <%= link_to 'START EXPLORING', new_jungle_path, class: "btn btn-warning" %>

    </div>


    <div class="col-4 ">


      <%= image_tag "plant-5.jpg", width: 350, height: 500, class: "plant-5" %>
      <%= image_tag "plant-room.jpg", width: 350, height: 400, class: "imgs-plants" %>

      <%= image_tag "plant-4.jpg", width: 350, height: 250, class: "plant-4" %>


    </div>

    </div>

</div>



<div class="sections">
  <%= render 'sections' %>
</div>

app/views/plants/edit.html.erb
 <%= simple_form_for([@jungle, @plant]) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

       <div class="form-inputs">
            <%= f.input :nickname %>
            <%= f.input :name,  placeholder: 'what kind of platn is it?' %>

          </div>

          <div class="form-actions">
            <%= f.button :submit, 'edit plant', class: "btn btn-primary" %>
          </div>
      <% end %>

app/views/plants/new.html.erb
 <%= simple_form_for([@jungle, @plant]) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

       <div class="form-inputs">
            <%= f.input :nickname %>
            <%= f.input :name,  placeholder: 'what kind of platn is it?' %>
            <%= f.input :image,  placeholder: 'add url' %>


          </div>

          <div class="form-actions">
            <%= f.button :submit, 'add plant', class: "btn btn-primary" %>
          </div>
      <% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <A> ABOUT </A>
    <A> FAQ </A>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>

  </div>
  <a href="https://www.freepik.com/vectors/background">Background vector created by visnezh - www.freepik.com</a>
  <div class="footer-copyright">
    UrbanJungles <i class="fas fa-leaf"></i>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm  navbar-lewagon fixed-top <% yield(:navbar_class) %>">
  <%= link_to "urbanjunglesclub.", root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>